### ISSUE TITLE
User Input axis problems with keyboard source

### ISSUE THREAD

**Issue by MalpenZibo** [MalpenZibo/ZENgine#60]
**Describe the bug**
When user input is defined like this
``` yml
axis_mappings: 
  X: 
  - source:
      Keyboard:
        key: D
     scale: 1.0
  - source:
      Keyboard:
        key: A
     scale: -1.0
```

When A Key is down `InputHandler.axis_value(UserInput::X)` return correctly -1 but when the D key is clicked (down and then up, A key is still down), `InputHandler.axis_value(UserInput::X)` no longer return -1.
